name: 'Pecans - Ponca City, OK. 74601 in Kay County'
favicon: null
layout_spectrum: 0.24646
typography_spectrum: 0.80112
title: Merry Pecans
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfefd'
    - '#020202'
    - '#c3af87'
    - '#7f2d0c'
    - '#bc773f'
  brandStrength: 0.75
  lightness: 0.2911579543724656
  saturation: 0.7152385641820729
  rhythmicContrast: 0.5908071408048272
purpose: []
