name: Pecans
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1014
title: 'Very Merry Pecans in Ponca City, OK.  Kay County'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff0104'
    - '#014708'
    - '#029c35'
    - '#fd5848'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
