name: 'Pecans - Ponca City, OK. 74601 in Kay County'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.80112
title: 'Very Merry Pecans in Ponca City, OK.  Kay County'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#232323'
    - '#8e7353'
    - '#aca577'
    - '#d2e2f8'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
